### ISSUE TITLE
Adding Nico in the committee

### ISSUE THREAD

**Issue by malvikasharan** [open-life-science/ols-governance#3]
### TODO for Nico

- [ ] Review in your time: docs: https://github.com/open-life-science/ols-governance/tree/main/docs
- [ ] Bio update: if you need to update

### TODO for Malvika

- [ ] Add Nico on the governance page: https://openlifesci.org/people.html

### TODO for Camille
- [ ] Add Nico in email, Slack, Calendar - for @Camille-Gonz-VA to do
- [ ] Remove Laura from Email, Slack, Calendar (as Nico will replace her in the committee) - for @Camille-Gonz-VA

**Comment by yochannah** [comment]
Nico is long-term unavailable.

**Comment by yochannah** [comment]
Nico came back :) 

@npalopoli - are you happy with your profile on the OLS site?

**Comment by NPalopoli** [comment]
Thank you Yo! Happy to be back. I'll go through the documents asap.

I´m happy with the profile (here, right? https://we-are-ols.org/governance.html), but since you ask, please consider changing "Universidad Nacional De Quilmes & Conicet" for "Universidad Nacional de Quilmes - CONICET & MetaDocencia" (or if it´s too long for the design, "UNQ-CONICET & MetaDocencia"). 

Also please link to my current website, [https://npalopoli.github.io](https://npalopoli.github.io/) instead.

I´m happy if you do the changes when it suits you, so as not to conflict with how you prefer to update the code, but I can also do it myself if you prefer.

Thanks!

**Comment by yochannah** [comment]
if you have the energy to do it, go for it my friend!! :)

**Comment by NPalopoli** [comment]
I can do -- but would you please point me to the right file to edit?

**Comment by NPDebs** [comment]
Sure thing, @yochannah.

Hey, @NPalopoli. 👋  Nice to GitHub-meet you!

About the files you need to edit:
- Your **bio** is sitting pretty at line 9100 of our [people.yaml](https://github.com/open-life-science/open-life-science.github.io/blob/06f73e0a833e56816f3c6be161d921c6233f7a2b/_data/people.yaml#L9100) file.
- The names displayed in the _governance_ section are found in the `community.yaml` file - [line 22](https://github.com/open-life-science/open-life-science.github.io/blob/06f73e0a833e56816f3c6be161d921c6233f7a2b/_data/community.yaml#L22).

Tag me here or on Slack (`@Debs`) if you need to know anything else, okay?
